// React Project/Frontend/src/Components/Nav.jsx
// Title : FLIGHT BOOKING
// Author : TAMILARASAN M
// Created At : 24-06-2024
// Last Modified Date : 08-08-2024
// Reviewed By :
// Review Date :

import React from 'react'
import '../styles/style.css';
import { Link } from 'react-router-dom';

function Nav() {
  return (
    <div>
        <nav className="nav_bar">
        <div className="nav__logo">FLIGHT BOOKING</div>
        <ul className="nav__links">
          <li className="link"><Link to="/home">Home</Link></li>
          <li className="link"><Link to="/destinations">Popular Destinations</Link></li>
          <li className="link"><Link to="/mybookings">MY Bookings</Link></li>
          <li className="link"><a href="#about_footer">About</a></li>
        </ul>
        <Link to="/"><button className="btn">LOGOUT</button></Link>
      </nav>
    </div>
  )
}

export default Nav

// Angular Project/Frontend/src/app/nav/nav.component.ts
// Title : FLIGHT BOOKING
// Author : TAMILARASAN M
// Created At : 24-03-2024
// Last Modified Date : 08-06-2024
// Reviewed By :
// Review Date :

import { Component } from '@angular/core';

@Component({
  selector: 'app-nav',
  standalone: true,
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.css']
})
export class NavComponent {
}

 <!-- Title : FLIGHT BOOKING
 Author : TAMILARASAN M
 Created At : 24-03-2024
 Last Modified Date : 08-06-2024
 Reviewed By :
 Review Date : -->

<nav class="nav_bar">
  <div class="nav__logo">FLIGHT BOOKING</div>
  <ul class="nav__links">
    <li class="link"><a href="/home">Home</a></li>
    <li class="link"><a href="/destinations">Popular Destinations</a></li>
    <li class="link"><a href="/mybookings">MY Bookings</a></li>
    <li class="link"><a>About</a></li>
  </ul>
  <button class="btn"><a href="" style="color: white;">LOGOUT</a></button>
</nav>
