// Angular Project/Frontend/src/app/login/login.component.ts
// Title : FLIGHT BOOKING
// Author : TAMILARASAN M
// Created At : 24-03-2024
// Last Modified Date : 08-06-2024
// Reviewed By :
// Review Date :

import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { catchError } from 'rxjs/operators';
import { of } from 'rxjs';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';

@Component({
  selector: 'app-login',
  standalone: true,
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  imports: [CommonModule, ReactiveFormsModule]
})
export class LoginComponent {
  loginForm: FormGroup;
  msg: string = '';
  msgType: string = '';

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      userName: ['', Validators.required],
      password: ['', Validators.required]
    });
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      const { userName, password } = this.loginForm.value;

      this.http.post<any>('http://localhost:8000/auth/login', { userName, password })
        .pipe(
          catchError(error => {
            console.error('Error:', error);
            this.msg = 'Internal server error';
            this.msgType = 'error';
            return of(null);
          })
        )
        .subscribe(data => {
          if (data && data.msg) {
            this.msg = data.msg;
            this.msgType = data.msg_type;
            if (data.msg_type === 'success') {
              this.router.navigate(['/home']);
            }
          }
        });
    }
  }
}

 <!-- Title : FLIGHT BOOKING
 Author : TAMILARASAN M
 Created At : 24-03-2024
 Last Modified Date : 08-06-2024
 Reviewed By :
 Review Date : -->

<div class="formcontainer">
  <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" id="form">
    <h3 style="text-align: center; font-family: 'Lobster', cursive; font-size: 30px; color: #000;">
      FLIGHT BOOKING
    </h3>
    <h1 style="text-align: center; font-size: 20px; color: #000;">LOGIN</h1>
    <p *ngIf="msg" [ngClass]="msgType">{{ msg }}</p>
    <div class="input-group">
      <input formControlName="userName" id="username" placeholder="Username" required />
    </div>
    <div class="input-group">
      <input formControlName="password" id="password" placeholder="Password" type="password" required />
    </div>
    <button class="login" type="submit">LOGIN</button>
    <p class="signup_button">Not a member? <a href="/register">Signup</a></p>
  </form>
</div>

// React Project/Frontend/src/Components/Login.jsx
// Title : FLIGHT BOOKING
// Author : TAMILARASAN M
// Created At : 24-06-2024
// Last Modified Date : 08-08-2024
// Reviewed By :
// Review Date :

import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom'; 
import '../styles/style.css'; 

const Login = () => {
  const [msg, setMsg] = useState('');
  const [msgType, setMsgType] = useState('');
  const navigate = useNavigate(); 

  const handleSubmit = async (event) => {
    event.preventDefault();
    const userName = event.target.userName.value;
    const password = event.target.password.value;

    try {
      const response = await fetch('http://localhost:5000/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userName, password })
      });

      const data = await response.json();
      if (response.ok) {
        setMsg(data.msg);
        setMsgType(data.msg_type);
        navigate('/home'); 
      } else {
        setMsg(data.msg);
        setMsgType(data.msg_type);
      }
    } catch (error) {
      console.error('Error:', error);
      setMsg('Internal server error');
      setMsgType('error');
    }
  };

  return (
    <div className="formcontainer">
      <form onSubmit={handleSubmit} id="form">
        <h3 style={{ textAlign: 'center', fontFamily: 'Lobster, cursive', fontSize: '30px', color: '#000' }}>
          FLIGHT BOOKING
        </h3>
        <h1 style={{ textAlign: 'center', fontSize: '20px', color: '#000' }}>LOGIN</h1>
        {msg && <p className={msgType}>{msg}</p>} 
        <div className="input-group">
          <input type="text" name="userName" id="username" placeholder="Username" required />
        </div>
        <div className="input-group">
          <input type="password" name="password" id="password" placeholder="Password" required />
        </div>
        <button className="login" type="submit">LOGIN</button>
        <p className="signup_button">Not a member? <Link to="/register">Signup</Link></p>
      </form>
    </div>
  );
};

export default Login;
