// Angular Project/Frontend/src/app/register/register.component.ts
// Title : FLIGHT BOOKING
// Author : TAMILARASAN M
// Created At : 24-03-2024
// Last Modified Date : 08-06-2024
// Reviewed By :
// Review Date :

import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-register',
  standalone: true,
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
  imports: [CommonModule, FormsModule]
})
export class RegisterComponent {
  msg: string = '';
  msgType: string = '';

  constructor(private http: HttpClient, private router: Router) {}

  handleSubmit(event: Event) {
    event.preventDefault();
    const form = event.target as HTMLFormElement;
    const userName = (form.elements.namedItem('userName') as HTMLInputElement).value;
    const email = (form.elements.namedItem('email') as HTMLInputElement).value;
    const password = (form.elements.namedItem('password') as HTMLInputElement).value;
    const confirmPassword = (form.elements.namedItem('confirmPassword') as HTMLInputElement).value;

    this.http.post<{ msg: string; msg_type: string }>('http://localhost:8000/auth/register', {
      userName,
      email,
      password,
      confirmPassword
    }).subscribe({
      next: (data) => {
        this.msg = data.msg;
        this.msgType = data.msg_type;
        if (data.msg_type === 'success') {
          this.router.navigate(['/']);
        }
      },
      error: (error) => {
        console.error('Error:', error);
        this.msg = 'Internal server error';
        this.msgType = 'error';
      }
    });
  }
}

 <!-- Title : FLIGHT BOOKING
 Author : TAMILARASAN M
 Created At : 24-03-2024
 Last Modified Date : 08-06-2024
 Reviewed By :
 Review Date : -->

<div class="formcontainer-2">
  <form (submit)="handleSubmit($event)" class="form2">
    <h3 style="text-align: center; font-family: Lobster, cursive; font-size: 30px; color: #000;">
      FLIGHT BOOKING
    </h3>
    <h1 style="text-align: center; font-size: 20px; color: #000;">SIGNUP</h1>
    <p *ngIf="msg" [ngClass]="msgType">{{ msg }}</p>
    <input type="text" name="userName" id="userName" placeholder="Username" required />
    <input type="email" name="email" id="email" placeholder="Email" required />
    <input type="password" name="password" id="password" placeholder="Password" required />
    <input type="password" name="confirmPassword" id="confirmPassword" placeholder="Confirm Password" required />
    <button class="signup" type="submit">SIGNUP</button>
    <p class="login_here">
      Already have an account? <a href="/">Login here</a>
    </p>
  </form>
</div>

// React Project/Frontend/src/Components/Register.jsx
// Title : FLIGHT BOOKING
// Author : TAMILARASAN M
// Created At : 24-06-2024
// Last Modified Date : 08-08-2024
// Reviewed By :
// Review Date :

import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import '../styles/style.css'; 

const Register = () => {
  const [msg, setMsg] = useState('');
  const [msgType, setMsgType] = useState('');

  const handleSubmit = async (event) => {
    event.preventDefault();
    const userName = event.target.userName.value;
    const email = event.target.email.value;
    const password = event.target.password.value;
    const confirmPassword = event.target.confirmPassword.value;

    try {
      const response = await fetch('http://localhost:5000/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userName, email, password, confirmPassword })
      });

      const data = await response.json();
      if (response.ok) {
        setMsg(data.msg);
        setMsgType(data.msg_type);
      } else {
        setMsg(data.msg);
        setMsgType(data.msg_type);
      }
    } catch (error) {
      console.log(error);
      console.error('Error:', error);
      setMsg('Internal server error');
      setMsgType('error');
    }
  };

  return (
    <div className="formcontainer-2">
      <form onSubmit={handleSubmit} className="form2">
        <h3 style={{ textAlign: 'center', fontFamily: 'Lobster, cursive', fontSize: '30px', color: '#000' }}>
          FLIGHT BOOKING
        </h3>
        <h1 style={{ textAlign: 'center', fontSize: '20px', color: '#000' }}>SIGNUP</h1>
        {msg && <p className={msgType}>{msg}</p>}
        <input type="text" name="userName" id="userName" placeholder="Username" required />
        <input type="email" name="email" id="email" placeholder="Email" required />
        <input type="password" name="password" id="password" placeholder="Password" required />
        <input type="password" name="confirmPassword" id="confirmPassword" placeholder="Confirm Password" required />
        <button className="signup" type="submit">SIGNUP</button>
        <p className="login_here">
          Already have an account? <Link to="/">Login here</Link>
        </p>
      </form>
    </div>
  );
};

export default Register;
