// React Project/Frontend/src/Components/Payment.jsx
// Title : FLIGHT BOOKING
// Author : TAMILARASAN M
// Created At : 24-06-2024
// Last Modified Date : 08-08-2024
// Reviewed By :
// Review Date :

import React, { useState, useEffect } from 'react';
import '../styles/payment.css';
import '../styles/style.css'; 
import Nav from './Nav';
import { useNavigate } from 'react-router-dom';

const Payment = () => {
    const [flightPrice, setFlightPrice] = useState('Rs.1000');
    const [cardNumber, setCardNumber] = useState('');
    const [cardHolder, setCardHolder] = useState('');
    const [expirationMM, setExpirationMM] = useState('');
    const [expirationYY, setExpirationYY] = useState('');
    const [cvv, setCvv] = useState('');

    const navigate = useNavigate(); 

    useEffect(() => {
        const storedPrice = localStorage.getItem('flightPrice');
        if (storedPrice) {
            setFlightPrice(`Rs.${storedPrice}`);
        }
    }, []);

    const handleSubmit = async (event) => {
        event.preventDefault();
        if (!cardNumber || !cardHolder || !expirationMM || !expirationYY || !cvv) {
            alert('Please fill in all fields before submitting.');
        } else {
            try {
                const response = await fetch('http://localhost:5000/auth/payment', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        cardNumber,
                        cardHolder,
                        expirationMM,
                        expirationYY,
                        CVV: cvv
                    }),
                });

                const data = await response.json();
                if (response.ok) {
                    alert(data.msg);
                    navigate('/confirm'); 
                } else {
                    alert(data.msg);
                }
            } catch (error) {
                console.error('Error:', error);
                alert('Internal server error');
            }
        }
    };

    return (
        <div className="pay_body">
            <Nav />
            <div className="pay_container">
                <div className="pay_header"><h1>PAYMENT</h1></div>
                <div className="pay_info">
                    <form className="payment_form" onSubmit={handleSubmit}>
                        <div>
                            <label htmlFor="CardNumber">Card Number</label>
                            <input
                                type="number"
                                className="big-btn"
                                name="CardNumber"
                                id="CardNumber"
                                placeholder="Enter Card Number"
                                value={cardNumber}
                                onChange={(e) => setCardNumber(e.target.value)}
                                required
                            />
                        </div>
                        <div>
                            <label htmlFor="CardHolder">Card Holder</label>
                            <input
                                type="text"
                                className="big-btn"
                                name="CardHolder"
                                id="CardHolder"
                                placeholder="Enter Card Holder"
                                value={cardHolder}
                                onChange={(e) => setCardHolder(e.target.value)}
                                required
                            />
                        </div>
                        <div>
                            <label htmlFor="ExpirationMM">Expiration MM</label>
                            <label htmlFor="Expirationyy">Expiration YY</label>
                            <label htmlFor="CVV">CVV</label>
                            <label htmlFor="Price">Total Price</label>
                        </div>
                        <div>
                            <input
                                type="number"
                                className="under-input"
                                name="ExpirationMM"
                                id="ExpirationMM"
                                placeholder="Enter Exp MM"
                                min="1"
                                max="12"
                                value={expirationMM}
                                onChange={(e) => setExpirationMM(e.target.value)}
                                required
                            />
                            <input
                                type="number"
                                className="under-input"
                                name="Expirationyy"
                                id="Expirationyy"
                                placeholder="Enter Exp YY"
                                min="2024"
                                max="2050"
                                value={expirationYY}
                                onChange={(e) => setExpirationYY(e.target.value)}
                                required
                            />
                            <input
                                type="number"
                                className="under-input"
                                name="CVV"
                                id="CVV"
                                placeholder="Enter CVV"
                                value={cvv}
                                onChange={(e) => setCvv(e.target.value)}
                                required
                            />
                            <p className="Total_Price" id="tp">{flightPrice}</p>
                        </div>
                        <div className="pay_btn">
                            <button type="submit" id="pay-submit">SUBMIT</button>
                        </div>
                    </form>
                </div>
                <img src="/images/bankCard.png" alt="PAYMENT" className="pay1-img" />
            </div>
        </div>
    );
};

export default Payment;

// Angular Project/Frontend/src/app/payment/payment.component.ts
// Title : FLIGHT BOOKING
// Author : TAMILARASAN M
// Created At : 24-03-2024
// Last Modified Date : 08-06-2024
// Reviewed By :
// Review Date :

import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { NavComponent } from '../nav/nav.component';

@Component({
  selector: 'app-payment',
  standalone: true,
  imports: [CommonModule, FormsModule, NavComponent],
  templateUrl: './payment.component.html',
  styleUrls: ['./payment.component.css']
})
export class PaymentComponent {
  flightPrice: string = 'Rs.1000';
  cardNumber: string = '';
  cardHolder: string = '';
  expirationMM: string = '';
  expirationYY: string = '';
  cvv: string = '';

  constructor(private router: Router, private http: HttpClient) {}

  ngOnInit(): void {
    const storedPrice = localStorage.getItem('flightPrice');
    if (storedPrice) {
      this.flightPrice = `Rs.${storedPrice}`;
    }
  }

  handleSubmit(event: Event): void {
    event.preventDefault();

    if (!this.cardNumber || !this.cardHolder || !this.expirationMM || !this.expirationYY || !this.cvv) {
      alert('Please fill in all fields before submitting.');
    } else {
      this.http.post('http://localhost:8000/auth/payment', {
        cardNumber: this.cardNumber,
        cardHolder: this.cardHolder,
        expirationMM: this.expirationMM,
        expirationYY: this.expirationYY,
        CVV: this.cvv
      }).subscribe({
        next: (response: any) => {
          if (response.msg_type === 'success') {
            alert(response.msg);
            this.router.navigateByUrl('/confirm');
          } else {
            alert('Payment failed. Please try again.');
          }
        },
        error: (error) => {
          console.error('Error:', error);
          alert('Internal server error');
        }
      });
    }
  }

}

 <!-- Title : FLIGHT BOOKING
 Author : TAMILARASAN M
 Created At : 24-03-2024
 Last Modified Date : 08-06-2024
 Reviewed By :
 Review Date : -->

<app-nav></app-nav>
<div class="pay_body">
  <div class="pay_container">
    <div class="pay_header"><h1>PAYMENT</h1></div>
    <div class="pay_info">
      <form class="payment_form" (submit)="handleSubmit($event)">
        <div>
          <label for="CardNumber">Card Number</label>
          <input
            type="number"
            class="big-btn"
            name="CardNumber"
            id="CardNumber"
            placeholder="Enter Card Number"
            [(ngModel)]="cardNumber"
            required
          />
        </div>
        <div>
          <label for="CardHolder">Card Holder</label>
          <input
            type="text"
            class="big-btn"
            name="CardHolder"
            id="CardHolder"
            placeholder="Enter Card Holder"
            [(ngModel)]="cardHolder"
            required
          />
        </div>
        <div>
          <label for="ExpirationMM">Expiration MM</label>
          <label for="Expirationyy">Expiration YY</label>
          <label for="CVV">CVV</label>
          <label for="Price">Total Price</label>
        </div>
        <div>
          <input
            type="number"
            class="under-input"
            name="ExpirationMM"
            id="ExpirationMM"
            placeholder="Enter Exp MM"
            min="1"
            max="12"
            [(ngModel)]="expirationMM"
            required
          />
          <input
            type="number"
            class="under-input"
            name="Expirationyy"
            id="Expirationyy"
            placeholder="Enter Exp YY"
            min="2024"
            max="2050"
            [(ngModel)]="expirationYY"
            required
          />
          <input
            type="number"
            class="under-input"
            name="CVV"
            id="CVV"
            placeholder="Enter CVV"
            [(ngModel)]="cvv"
            required
          />
          <p class="Total_Price" id="tp">{{ flightPrice }}</p>
        </div>
        <div class="pay_btn">
          <button type="submit" id="pay-submit">SUBMIT</button>
        </div>
      </form>
    </div>
    <img src="/images/bankCard.png" alt="PAYMENT" class="pay1-img" />
  </div>
</div>
